[project]
name = "dglink"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gilda>=1.4.1",
    "ipdb>=0.13.13",
    "ipython>=8.37.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "synapseclient>=4.9.0",
]
